# Generated by Django 5.2.1 on 2025-05-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passw', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('interest1', models.CharField(blank=True, max_length=4, null=True)),
                ('interest2', models.CharField(blank=True, max_length=4, null=True)),
                ('interest3', models.CharField(blank=True, max_length=4, null=True)),
                ('kyc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('alpaca_account_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
