# Generated by Django 5.2.1 on 2025-05-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlpacaBrokerAccount',
        ),
    ]
